[package]
name = "rutel"
version = "0.1.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
tokio-core = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
#clippy = {version = "*", optional = true}
# rutel_derive = {version = "0.1.0", path = "./rutel_derive/"}
rutel_derive = { version = "0.1.0", git = "https://github.com/serbe/rutel-derive.git" }
clippy = "*"

# [features]
# default = []
