[package]
name = "rutel"
version = "0.5.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
netc = { version = "0.5", git = "https://github.com/serbe/netc" }
rutel_derive = { version = "0.4", git = "https://github.com/serbe/rutel_derive" }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "0.3", features = ["full"]}
dotenv = "0.15"
