[package]
name = "rutel"
version = "0.2.1"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rutel_derive = { version = "0.3.1", git = "https://github.com/serbe/rutel_derive" }
tsocks = { version = "0.4.1", git = "https://github.com/serbe/tsocks" }
