[package]
name = "rutel"
version = "0.2.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
# rutel_derive = {version = "0.3.0", path = "./rutel_derive/"}
rutel_derive = { version = "0.3.1", git = "https://github.com/serbe/rutel_derive.git" }
tsocks = { version = "0.3.3", git = "https://github.com/serbe/tsocks.git" }
# tsocks = { version = "0.3.1", path = "./tsocks/" }
