[package]
name = "rutel"
version = "0.3.3"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
rpc = { version = "0.1", git = "https://github.com/serbe/rpc" }
rutel_derive = { version = "0.4", git = "https://github.com/serbe/rutel_derive" }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"]}
